# Generated by Django 5.1.2 on 2024-10-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
